// Action Type Definitions
const GIPHY_GET_REQUEST = 'GIPHY_GET_REQUEST';
const GIPHY_GET_REQUEST_SINGLE = 'GIPHY_GET_REQUEST_SINGLE';
const GIPHY_GET_SUCCESS = 'GIPHY_GET_SUCCESS';
const GIPHY_GET_SUCCESS_SINGLE = 'GIPHY_GET_SUCCESS_SINGLE';

export {
  GIPHY_GET_REQUEST,
  GIPHY_GET_REQUEST_SINGLE,
  GIPHY_GET_SUCCESS,
  GIPHY_GET_SUCCESS_SINGLE,
};
