// Action Type Definitions
const DB_GET_FAILURE_ACCOUNT = 'DB_GET_FAILURE_ACCOUNT';
const DB_GET_REQUEST_ACCOUNT = 'DB_GET_REQUEST_ACCOUNT';
const DB_GET_SUCCESS_ACCOUNT = 'DB_GET_SUCCESS_ACCOUNT';
const DB_GET_SUCCESS_NO_DATA_ACCOUNT = 'DB_GET_SUCCESS_NO_DATA_ACCOUNT';
const DB_POST_FAILURE_ACCOUNT = 'DB_POST_FAILURE_ACCOUNT';
const DB_POST_REQUEST_ACCOUNT = 'DB_POST_REQUEST_ACCOUNT';
const DB_POST_SUCCESS_ACCOUNT = 'DB_POST_SUCCESS_ACCOUNT';
const DB_POST_SUCCESS_NO_DATA_ACCOUNT = 'DB_POST_SUCCESS_NO_DATA_ACCOUNT';

const DB_GET_FAILURE_GIFS = 'DB_GET_FAILURE_GIFS';
const DB_GET_REQUEST_GIFS = 'DB_GET_REQUEST_GIFS';
const DB_GET_SUCCESS_GIFS = 'DB_GET_SUCCESS_GIFS';
const DB_RESET_GIFS = 'DB_RESET_GIFS';

export {
  DB_GET_FAILURE_ACCOUNT,
  DB_GET_REQUEST_ACCOUNT,
  DB_GET_SUCCESS_ACCOUNT,
  DB_GET_SUCCESS_NO_DATA_ACCOUNT,
  DB_POST_FAILURE_ACCOUNT,
  DB_POST_REQUEST_ACCOUNT,
  DB_POST_SUCCESS_ACCOUNT,
  DB_POST_SUCCESS_NO_DATA_ACCOUNT,
  DB_GET_FAILURE_GIFS,
  DB_GET_REQUEST_GIFS,
  DB_GET_SUCCESS_GIFS,
  DB_RESET_GIFS,
};
